[WIP] add fine-tuning codebase toward StableLM-JP-Tuned-Alpha
Stability-AI/gpt-neox pull request #4
Opened 2023-05-19 01:44 UTC by fujiki-saij

2023-05-25 08:21 UTC, leemengtw reviewed
@fujiki-saij except some small changes are needed, generally LGTMeng. Feel free to merge after considering my comments, thanks!

2023-05-25 08:21 UTC, leemengtw commented on finetune/configs/sample.yaml
> +max_text_len": 1024
let's remove the additional `"` here.

2023-05-25 08:21 UTC, leemengtw commented on finetune/configs/sample.yaml
> +  save_total_limit": 2
currently passing this key to training config will raise error, could you double check whether we need to rename or remove it?

2023-05-25 08:21 UTC, leemengtw commented on finetune/finetune_base_ja.py
> +        )
2 changes might be needed here:
1. change `config["tokenizer_path"]` to `config["tokenizer"]["tokenizer_name_or_path"]` to match with what you have in `sample.yaml`
2. maybe remove the `if` statement and just use a general purpose one:

```python
tokenizer = AutoTokenizer.from_pretrained(
            config["tokenizer"]["tokenizer_name_or_path"], use_fast=config.get("use_fast", False), cache_dir=config.get("cache_dir", None),
        )
```

2023-05-25 08:45 UTC, leemengtw commented on finetune/rm_datasets.py
> +        #         return
oh yap maybe clean up a little bit and add back the cache feature. Right now `cache_name` param is not used and the cache it would be helpful for debugging purpose 👍

2023-05-25 08:47 UTC, leemengtw commented on finetune/finetune_base_ja.py
> +            if example[k].startswith("「") and example[k].endswith("」"):
JFYI when I run the program, this `if` statement was never triggered.

2023-05-25 08:48 UTC, fujiki-saij commented on finetune/configs/sample.yaml
> +  save_total_limit": 2
OK, let me double check these configurations. (I just manually translated the config to this yaml format, so there might be some mistakes.)

2023-05-25 08:50 UTC, fujiki-saij commented on finetune/finetune_base_ja.py
> +            if example[k].startswith("「") and example[k].endswith("」"):
That's right. I've already updated the dataset at HF by applying this processing.
So, we don't need this functionality here now.

2023-05-25 08:54 UTC, fujiki-saij commented on finetune/finetune_base_ja.py
> +        )
I thought I already committed and pushed this change, but actually just staged and forgot to commit and push it.
https://github.com/Stability-AI/gpt-neox/pull/4/commits/0691ffaebfc803a92ff2be9d9f5d47897ca75067
Thanks for the review!

2023-05-26 17:52 UTC, leemengtw requested changes

2023-05-26 17:52 UTC, leemengtw commented on finetune/templates.py
> +NO_INPUT_PROMPT = """以下は、タスクを説明する指示と、文脈のある入力の組み合わせです。要求を適切に満たす応答を書きなさい。
@fujiki-saij  I think we should modify this instruction because there is no `文脈のある入力` so the `文脈のある入力の組み合わせ` is incorrect and we might get better result with improved instruction.

2023-05-28 05:31 UTC, fujiki-1emon commented on finetune/templates.py
> +NO_INPUT_PROMPT = """以下は、タスクを説明する指示と、文脈のある入力の組み合わせです。要求を適切に満たす応答を書きなさい。
OK. Let me add prompt template versioning functionality to experiment with different templates (in this PR or another PR).

2023-05-30 06:02 UTC, merged