Add MeCabTokenizer config
Stability-AI/gpt-neox pull request #9
Opened 2023-05-22 09:59 UTC by polm-stability

This adds a config using the MeCabTokenizer for two-pass tokenization.

It also fixes the permissions on an existing config.

2023-05-22 11:00 UTC, leemengtw commented on configs/stable-lm-jp/stable-lm-jp-1b-unidiclite_tok-mc4-cc100_wiki.yml
> +  "load": "/fsx/jp-llm/ckpts/1b_tok=nai_data=mc4-cc100-wiki_bs=4m_tp=1_pp=1_init=wang-small-init_dtype=int64",
These 2 keys specify the path to save/load checkpoints. Let's make sure there are unique and will not read/overwrite checkpoints with other models.

2023-05-22 11:00 UTC, leemengtw commented on configs/stable-lm-jp/stable-lm-jp-1b-unidiclite_tok-mc4-cc100_wiki.yml
> +  "wandb_name": "1B.nai.mc4_cc100_wiki.bs_4m.tp_1.dtype_int64",
Let's update this to reflect the tokenizer change. May something like `1B.mecab.mc4_cc100_wiki.bs_4m.tp_1.dtype_int64` ?

2023-05-22 11:00 UTC, leemengtw commented on configs/stable-lm-jp/stable-lm-jp-1b-unidiclite_tok-mc4-cc100_wiki.yml
> +  "eval_tasks": [
I think this is okay for some quick experiment but JFYI if you want to compare with some other JP models we're training with NAI tokenizer, please refer to [this example conf](https://github.com/Stability-AI/gpt-neox/blob/9be317758877b24cfb2d0f1191a8a138a4f03479/configs/stable-lm-jp/stable-lm-jp-3b-nai_tok-ja50_rp50.yml#L79) that available in `feat/eval-logging-improvement` that will soon be merged in `jp-stable`

2023-05-23 03:33 UTC, polm-stability commented
Thanks for the feedback! I made this by copying another config and just changing two lines related to the tokenization settings, so I wasn't sure what else needed updating. I think this should be OK now?

2023-05-23 05:02 UTC, leemengtw requested changes
Almost done! Let's add 2 additional keys for evaluation setting.

2023-05-23 05:02 UTC, leemengtw commented on configs/stable-lm-jp/stable-lm-jp-1b-unidiclite_tok-mc4-cc100_wiki.yml
> +  "eval_tasks": [
Let's add 

```json
"eval_num_fewshot": [
        3,
        3,
        3
    ],
    "eval_limit": [
        0.25,
        0.25,
        0.25
    ],
``` 

under the `eval_tasks` key to make sure we're using the exact setting (#few shots, sample ratio) when doing evaluation.

2023-05-23 05:49 UTC, polm-stability commented
OK, added!

2023-05-23 06:12 UTC, leemengtw approved these changes
LGTM

2023-05-23 06:38 UTC, polm-stability commented
OK, I'll merge this, though let's not start training without further discussion.

2023-05-23 06:38 UTC, merged